name: 'Automatic build'
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'

jobs:
  build-n-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Site
        run: |
          bash tools/build.sh -b ""

      - name: Test Site
        run: |
          bash tools/test.sh

  deploy:
    needs: build-n-test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: |
          bash tools/build.sh

      - name: Deploy
        run: |
          bash tools/deploy.sh
